package com.codeloom.dsa.analytics.entity;

public enum ActivityType {
    PROBLEM_SOLVED,
    ALGORITHM_COMPLETED,
    ALGORITHM_VISUALIZATION,
    DAILY_CHALLENGE_COMPLETED,
    PRACTICE_SESSION_COMPLETED,
    STREAK_MILESTONE,
    ACHIEVEMENT_UNLOCKED,
    BADGE_UNLOCKED,
    LEVEL_UP
}
